Revamp tests almost completely

diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -1,55 +1,60 @@
 #!/usr/bin/env bash
 
-failIfDifferent() {
-    if diff -q "$1" "$2" &> /dev/null; then
-        echo "pass"
-    else
-        echo "FAIL"
-    fi
+TMPFILE=$(mktemp)
+
+error() {
+	CODE=$?
+	if [ $CODE ]; then
+		echo "pass"
+	else
+		echo "FAIL"
+	fi
 }
 
-prompt() {
-    echo "Press enter to continue."
-    # shellcheck disable=SC2034
-    read line
-    echo ""
-    echo ""
+VIM_ARGS="-e"
+bvim() {
+	#echo vim $* +"noatocmd wq! ${TMPFILE}" >&2
+	#vim -e $* +"noautocmd wq! ${TMPFILE}" > /dev/null
+	vim $VIM_ARGS $* +"noautocmd wq! ${TMPFILE}" &> /dev/null
+	cat "${TMPFILE}"
 }
+
+
+# https://stackoverflow.com/a/28563534
 
 cd "${0%/*}"
 echo "Edit the text file without Hexmode."
-prompt
-vim uncompressed.txt
+[ "$(bvim uncompressed.txt)" == "$(cat uncompressed.txt)" ]; error
+
 echo "Edit the text file with Hexmode."
-prompt
-vim -b uncompressed.txt
+[ "$(bvim -b uncompressed.txt)" == "$(xxd uncompressed.txt)" ]; error
+
 echo "Edit the compressed file without Hexmode"
-prompt
-vim compressed.txt.gz
+[ "$(bvim compressed.txt.gz)" == "$(gzip --uncompress --to-stdout compressed.txt.gz)" ]; error
+
 echo "Edit the compressed file as binary. Again, gzip should win and no hex should be shown."
-prompt
-vim -b compressed.txt.gz
+[ "$(bvim -b compressed.txt.gz)" == "$(gzip --uncompress --to-stdout compressed.txt.gz)" ]; error
+
 echo "Edit a zip file without Hexmode."
-prompt
-vim zipfile.zip
+[[ "$(bvim zipfile.zip)" =~ "zip.vim version" ]]; error
+
 echo "Edit a zip file as binary. Zip plugin should win, no hex should be shown."
-prompt
-vim -b zipfile.zip
+[[ "$(bvim -b zipfile.zip)" =~ "zip.vim version" ]]; error
+
 echo "Edit a tar file without Hexmode."
-prompt
-vim tarfile.tar
+[[ "$(bvim tarfile.tar)" =~ "tar.vim version" ]]; error
+#vim tarfile.tar
+
 echo "Edit a tar file as binary. Tar plugin should win, no hex should be shown."
-prompt
-vim -b tarfile.tar
+[[ "$(bvim -b tarfile.tar)" =~ "tar.vim version" ]]; error
 
 echo -n "A binary file doesn't change when saved ... "
+
 cp zipfile.zip binary-file
-vim -b -c ":wq" binary-file
-failIfDifferent zipfile.zip binary-file
+[ diff -q <(bvim -b binary-file) "zipfile.zip" &> /dev/null ]; error
 rm binary-file
 
 echo -n "An auto-detected binary file doesn't change when saved ... "
 cp zipfile.zip binary-file
-vim -c "let g:hexmode_autodetect = 1" -c ":wq" binary-file
-failIfDifferent zipfile.zip binary-file
+[ diff -q <(bvim -c "let g:hexmode_autodetect = 1" binary-file) "zipfile.zip" &> /dev/null ]; error
 rm binary-file
